baseurl = "https://j620656786206.github.io/"
languageCode = "en"
title = "A Developer, and A Cat"
theme = "Hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/mgjohansen\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
disqusShortname = "j620656786206"
googleAnalytics = "trackingcode"

[taxonomies]
tag = "tags"
category = "categories"

[languages]
  [languages.zh-tw]
    title = "工程師與貓"
    baseURL = "https://j620656786206.github.io/"
    weight = 1
    [languages.zh-tw.params]
      linkedin = "zh-tw-link"
  [languages.en]
    title = "A Developer, and A cat"
    baseURL = "https://j620656786206.github.io/en/"
    weight = 2
    [languages.en.params]
      linkedin = "english-link"
  

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "Alex Yu"
sharingicons = true
displayauthor = true
customCSS = ['custom.css']

[[params.menu]]
name = "home"
url = "#"
fa_icon = "fa-home"

[[params.menu]]
name = "globe"
url = "/en"
fa_icon = "fa-globe"

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/j620656786206"
fa_icon = "fa-github"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

