baseurl = "https://j620656786206.github.io/"
DefaultContentLanguage = "zh-tw"
theme = "Hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/mgjohansen\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
disqusShortname = "j620656786206"
googleAnalytics = "trackingcode"

[taxonomies]
tag = "tags"
category = "categories"

[languages]
  [languages.zh-tw]
    title = "工程師與貓"
    description = "程式筆記, 曬貓照, 美食分享"
    languageCode = "zh-tw"
    weight = 1
    [[languages.zh-tw.params.menu]]
      name = "首頁"
      url = "#"
      fa_icon = "home"
      weight = 2
    [[languages.zh-tw.params.menu]]
      name = "分類"
      url = "/categories"
      fa_icon = "th-large"
      weight = 3
    [[languages.zh-tw.params.menu]]
      name = "標籤"
      url = "/tags"
      fa_icon = "tag"
      weight = 4
    [[languages.zh-tw.params.menu]]
      name = "English"
      url = "/en"
      fa_icon = "globe"
      weight = 5
    [[languages.zh-tw.params.menu]]
      name = "github"
      url = "https://github.com/j620656786206"
      fa_icon = "github"
      weight = 6
    [[languages.zh-tw.params.menu]]
      name = "rss"
      url = "/index.xml"
      fa_icon = "rss"
      weight = 7

  [languages.en]
    title = "A Developer, and A cat"
    description = "Technology, Cat, Food"
    languageCode = "en"
    weight = 8
    [[languages.en.params.menu]]
      name = "home"
      url = "#"
      fa_icon = "home"
      weight = 9
    [[languages.en.params.menu]]
      name = "category"
      url = "/en/categories"
      fa_icon = "th-large"
      weight = 10
    [[languages.en.params.menu]]
      name = "tag"
      url = "/en/tags"
      fa_icon = "tag"
      weight = 11
    [[languages.en.params.menu]]
      name = "中文"
      url = "/"
      fa_icon = "globe"
      weight = 12
    [[languages.en.params.menu]]
      name = "github"
      url = "https://github.com/j620656786206"
      fa_icon = "github"
      weight = 13
    [[languages.en.params.menu]]
      name = "rss"
      url = "/index.xml"
      fa_icon = "rss"
      weight = 14
  
[params]

keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "Alex Yu"
sharingicons = true
displayauthor = true
customCSS = ['custom.css']

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

